### ISSUE TITLE
shortcut for host shell

### ISSUE THREAD

**Issue by fluoriteByte** [Vanilla-OS/desktop-image#108]
### Feature Description

This is a good idea if you are the type of person to mess up VSO pico (me) or want to access abroot without booting up the vso subsystem or other Miscellaneous stuff

### Rationale

I love messing with my abroot so much, that I'm tired of waiting for libpod to close when rebooting

also adb/fastboot/mtkclient/SP Flash tool works better outside of vso pico

### Additional Information

the desktop file:
```
[Desktop Entry]
Version=1.0
Type=Application
Terminal=true
Exec=/usr/bin/bash
Name=Rescue Terminal
Comment=Use this when something is stopping you from resetting VSO or when wanting to access the system shell. This does not guarantee any full write access to root.
Icon=org.gnome.Console
Categories=ConsoleOnly;System;
StartupWMClass=kgx
```

**Comment by taukakao** [comment]
An alternative approach would be adding an entry to the right click menu of the original Console desktop entry.

**Comment by taukakao** [comment]
I don't think this is possible with Black Box, which we switched to now.
Maybe we need to install two terminals. One for the container and one for the host shell.

**Comment by taukakao** [comment]
I think this is an important change but not strictly necessary for beta so I'll move this to after stable.
