### ISSUE TITLE
.apk files don't install

### ISSUE THREAD

**Issue by jacobgonzales20** [Vanilla-OS/desktop-image#111]
### Issue Description

.apk files using side loader don't install

### Steps to Reproduce

1. download a .apk (signal client)
2. sideload with utility 

### On what version of Vanilla OS this happens?

Unreleased

### Additional Information

# System Details Report
---

## Report details
- **Date generated:**                              2024-05-11 07:03:29

## Hardware Information:
- **Hardware Model:**                              Lenovo ThinkPad T14s Gen 1
- **Memory:**                                      16.0 GiB
- **Processor:**                                   AMD Ryzen™ 7 PRO 4750U with Radeon™ Graphics × 16
- **Graphics:**                                    AMD Radeon™ Graphics
- **Disk Capacity:**                               (null)

## Software Information:
- **Firmware Version:**                            R1CET77W(1.46 )
- **OS Name:**                                     Vanilla OS 2.0
- **OS Build:**                                    (null)
- **OS Type:**                                     64-bit
- **GNOME Version:**                               46
- **Windowing System:**                            Wayland
- **Kernel Version:**                              Linux 6.7.9-amd64

**Comment by mirkobrombin** [comment]
Tracking here https://github.com/Vanilla-OS/vanilla-system-operator/issues/112 Please reopen if the proposed fix doesn't work for you (once deployed).

**Comment by jacobgonzales20** [comment]
> Tracking here [Vanilla-OS/vanilla-system-operator#112](https://github.com/Vanilla-OS/vanilla-system-operator/issues/112) Please reopen if the proposed fix doesn't work for you (once deployed).

secure boot is disabled, same result still

**Comment by mirkobrombin** [comment]
what's the output? It should display an error, if not then try via terminal: `vso android install --local <path_to.apk>`

**Comment by Mannshoch** [comment]
I use Vanilla OS 2.0 fresh installed 
```
ERRO[0000] invalid internal status, try resetting the pause process with "podman system migrate": could not find any running process: no such process 
VSO Pico is not initialized. Do you want to initialize it now? (y/n)
y
ERRO[0000] invalid internal status, try resetting the pause process with "/usr/bin/podman system migrate": could not find any running process: no such process 
 INFO  VSO Subsystem wir initialisiert...
ERRO[0000] invalid internal status, try resetting the pause process with "podman system migrate": could not find any running process: no such process 
 WARNING  Fallback zur Host-Shell? Dies könnte zu unerwartetem Verhalten führen. [y/N]
y
USER@MyVanilla:~/Downloads$ ls
F-Droid.apk
USER@MyVanilla:~/Downloads$ vso android install --local  "/home/USER/Downloads/F-Droid.apk"
Error: container not found
Usage:
  vso android install [flags]

Flags:
  -h, --help        help for install
  -l, --local       Installiere eine lokale apk
  -y, --noconfirm   Bei der Installation nicht nach einer Bestätigung fragen

  ERROR   container not found
```
