### ISSUE TITLE
Replace GNOME Console with Blackbox

### ISSUE THREAD

**Issue by mirkobrombin** [Vanilla-OS/desktop-image#129]
..because GNOME Console is bugged, has flickering issues and whatever.

Also check: https://github.com/search?q=org%3AVanilla-OS%20kgx&type=code

**Comment by axtloss** [comment]
ptyxis makes more sense for our usecase, it was made for the container workflow we aim for

**Comment by mirkobrombin** [comment]
Also pretty much bugger at least from our tests

**Comment by axtloss** [comment]
we tested the development version, it has had a stable release since then

**Comment by mirkobrombin** [comment]
Yup but still have problems with dbox in general (from what Luca said)
