### ISSUE TITLE
feat: update GNOME Control Center to version 46

### ISSUE THREAD

**Issue by kbdharun** [Vanilla-OS/desktop-image#145]
Also we need to update the modules/tools like Vanilla Updates Utility and PRIME Utility.

---

Current module: https://github.com/Vanilla-OS/desktop-image/blob/main/modules/21-gnome-control-center.yml

**Comment by mirkobrombin** [comment]
It is already updated

![Image](https://github.com/Vanilla-OS/desktop-image/assets/9479903/1b5e609a-e6f1-4777-8bba-7ac0b3a99ebe)
