### ISSUE TITLE
Layout presets

### ISSUE THREAD

**Issue by mhanuszh** [Vanilla-OS/desktop-image#15]
First of all, it's more than likely that I'm creating this issues under the wrong repo, so sorry about that in advance.

To my knowledge, Vanilla OS ships with a vanilla Gnome setup. My question is, will there be layout presets?

For example, with only a few extensions and tweaks, Gnome can be turned into a very Windows like experience. This would be beneficial for non technical Windows refugees.

**Comment by Heus-Sueh** [comment]
I know what you're talking about, it would be interesting for Vanilla OS to have something similar to Zorin Appearance from Zorin OS
![image](https://github.com/Vanilla-OS/desktop-image/assets/98482469/83fa3267-87ff-491d-abe0-d06557d76526)

**Comment by axtloss** [comment]
We currently have no plans to add any form of gnome modifications that change the appearance of the shell and this will most likely not change in the future. 
Users are able to customize gnome to look the way they want it to look themselves, there are enough source on how to do that, and, if the need for one is big, users can always make their own version of the desktop-image with a modified gnome and maintain it for others to use.
