### ISSUE TITLE
Changing default shell in apx after recent changes

### ISSUE THREAD

**Issue by shuriken1812** [Vanilla-OS/desktop-image#172]
### Issue Description

In the Alpha builds when we changed the default shell (on the host) and then any newly created apx containers would respect and use that default shell.

With recent changes as now vso-shell is the default shell. Changing the shell in vso is not respected inside the apx containers. 

Also doing chsh inside the apx container has no effect. Probably due these distrobox changes since distrobox v1.4.0 

![Uploading Screenshot from 2024-07-22 22-54-07.png…]()

I am not sure which distrobox version is apx based on currently.

### Steps to Reproduce

Try doing `chsh -s /usr/bin/fish` or zsh inside the apx container or inside the vso-shell. apx container will keep using bash.

### On what version of Vanilla OS this happens?

Unreleased

**Comment by taukakao** [comment]
It's true that it doesn't respect the shell of the vso shell. But running "chsh -s /usr/bin/fish" works. If I exit the container and enter it again it does use fish.

**Comment by shuriken1812** [comment]
> It's true that it doesn't respect the shell of the vso shell. But running "chsh -s /usr/bin/fish" works. If I exit the container and enter it again it does use fish.

Thats not the case - 

![Screenshot from 2024-07-23 14-32-31](https://github.com/user-attachments/assets/26ccde4e-e43d-47c2-b062-d8653bef7b67)

**Comment by taukakao** [comment]
`chsh -s /usr/bin/fish` is the correct command. Running it with sudo will change the shell of the root user so running it without root should've been the correct command.

![grafik](https://github.com/user-attachments/assets/e6a5240f-76ad-47dc-9def-4755f1ead677)

I can't test it for the arch container, since it's broken as always.

Are you sure you're running the latest version? You can check with "apx -v", it should be "apx version v2.4.3"

**Comment by shuriken1812** [comment]
Indeed It was apx v2.4.1

And now with v2.4.3 shell change is working without an issue on fedora
However yes arch container is now broken which was not the case with apx v2.4.1

Probably we can take a look at that then.. closing this issue @taukakao
