### ISSUE TITLE
Hide non-useful system partitions  from Nautilus by default 

### ISSUE THREAD

**Issue by cleanerspam** [Vanilla-OS/desktop-image#188]
### Feature Description

In Nautilus you can see two partition one of 20Gb vaniila and one other partition

![Screenshot from 2024-07-31 09-03-37](https://github.com/user-attachments/assets/6dd944b0-ab54-4641-a2d5-fb81143aa421)

Please hide these partitions from normal user in Nautilus  

### Rationale

I dont think it is meant to be shown in Nautilus

**Comment by taukakao** [comment]
Those are two partitions on your device. I think it would be more confusing if they weren't there. 

Also, especially access fo the root of the filesystem can be very useful.

**Comment by cleanerspam** [comment]
Yes but what is vos-init one ?

**Comment by taukakao** [comment]
@cleanerspam 
This is where the kernel and initramfs are. 
While this may not be super useful for users I think it would be confusing it it can't be found anywhere.
But I don't have a strong opinion on that. It's fine for me if we remove it.
