### ISSUE TITLE
Update Files to 46.x

### ISSUE THREAD

**Issue by PlatonB** [Vanilla-OS/desktop-image#195]
### Feature Description

Vanilla OS 2 comes with Gnome 46, but Files (Nautilus) version is 45.

### Rationale

I assume the old version of Files is included inadvertently.

**Comment by taukakao** [comment]
Debian upgraded Nautilus quite late in Debian sid. 
We're stuck with the old files app until the next package sync, which should be rather soon tho.

**Comment by taukakao** [comment]
This issue is outdated. Files is already on 47.
