### ISSUE TITLE
Where can I find an offline installation package?

### ISSUE THREAD

**Issue by ZZH-Finalize** [Vanilla-OS/desktop-image#204]
### Feature Description

I need to install Vanilla OS2 on a computer without internet access, but the official installation package eventually connects to GitHub to download data. How can I complete these actions in advance?

### Rationale

I need to install Vanilla OS2 on a computer without internet access, but the official installation package eventually connects to GitHub to download data. How can I complete these actions in advance?

**Comment by bohrium2b** [comment]
As far as I know, there doesn't seem to be one yet. See https://github.com/Vanilla-OS/live-iso/issues/301.

**Comment by taukakao** [comment]
Closing because it's a duplicate of https://github.com/Vanilla-OS/live-iso/issues/301
