### ISSUE TITLE
`apx-vso-pico` Container Stuck in Stopping Status After Logout and Login

### ISSUE THREAD

**Issue by NN708** [Vanilla-OS/desktop-image#211]
### Issue Description

When I log out and then log back in, the `apx-vso-pico` container enters "stopping" status, which makes Black Box unusable.

### Steps to Reproduce

- Log out
- Log in
- Launch Black Box

### On what version of Vanilla OS this happens?

Vanilla OS 2 Orchid

**Comment by taukakao** [comment]
This issue seems resolved in the latest version.
Please reopen this issue if it still persists.
