### ISSUE TITLE
GNOME Software reports inexistant update for gnome-control-center-data

### ISSUE THREAD

**Issue by Blumoop** [Vanilla-OS/desktop-image#227]
### Issue Description

With the new update on Vanilla OS from yesterday, I have noticed that GNOME Software now says that there's a system update. I download it and then restart to apply it, it will go into the updating don't turn off your computer screen and be stuck at 0%. Once I'm back into the system the update seems to not be applied at all, and I can download it again. Has anyone else experienced this? 

### Steps to Reproduce

- Fresh install Vanilla OS
- Go to GNOME Software and you'll see that system updates are available
- Download and restart to apply the updates
- After updating, go back to the system and the system updates are still there in GNOME Software

### On what version of Vanilla OS this happens?

Vanilla OS 2 Orchid

### Additional Information

I have not have this happen before the update. Is it only supposed to update Flatpaks in GNOME Software and leave updating the system to the Vanilla OS tool?

**Comment by taukakao** [comment]
This might be a universal problem.
Could you click on "System Updates" and verify that it only lists "gnome-control-center-data"?

**Comment by Blumoop** [comment]
> This might be a universal problem. Could you click on "System Updates" and verify that it only lists "gnome-control-center-data"?

Yep, it only shows gnome-control-center-data.

**Comment by taukakao** [comment]
Ok, thank you.
This is a visual bug with our gnome software plugin. 
The package is not outdated, it's just reported incorrectly. 

Of course this will be fixed as soon as possible.
In the meantime, it's safe to ignore this supposed update.

**Comment by Blumoop** [comment]
No problem. Glad to help out!

**Comment by taukakao** [comment]
Turns out that it's not our plugin, it's the packagekit plugin which is reporting this. Should be an easy fix.
