### ISSUE TITLE
Epson stylus d120

### ISSUE THREAD

**Issue by Gmpgmpgmp** [Vanilla-OS/desktop-image#233]
### Issue Description

Non viene trovato il driver corrispondente alle stampante Epson stylus d120.

### Steps to Reproduce

Collegare la stampante.
Attendere che venga riconosciuta.

### On what version of Vanilla OS this happens?

Vanilla OS 2 Orchid

**Comment by taukakao** [comment]
Bug reports have to be written in English. Also, driver problems are usually a problem in debian and not VanillaOS.

Translation by deepl:
Le segnalazioni di bug devono essere scritte in inglese. Inoltre, i problemi di driver sono solitamente un problema di Debian e non di VanillaOS.
