### ISSUE TITLE
Arduino IDE does not discover Arduino board

### ISSUE THREAD

**Issue by trau-mar** [Vanilla-OS/desktop-image#234]
### Issue Description

The device /dev/ttyUSB0 is not created when plugging the Arduino board. This results in IDE not beeing able to discover the arduino board. I made sure that I am in the dialout group. One fact was strange: even with no apparent dialog beeing possible, the RX led of my arduino flashed regularly, so why was it receiving commands without any program running?

### Steps to Reproduce

connect arduino board e.g. UNO to your PC
ls /dev/t* to list all tty devices
no /dev/ttyUSB0 created, but should as with other systems
rx led of arduino flashing

### On what version of Vanilla OS this happens?

Vanilla OS 2 Orchid

### Additional Information

the problem could be solved for me with
abroot pkg remove brltty
abroot pkg apply
the reason for this is apparently that brltty starts even if there is no braille and blocks the /dev/ttyUSB0 (did not understand why)
A similar board with other serial chip set does not have the problem becaus it generates /dev/ttyACM0. this one is not affected and works normally even with brltty.
what I do not understand why brltty starts? seems to thing that arduino is a braille???
Imho, brltty should be banned out of the box, and only added for people with special needs.
now my arduino is programmable and works like a charm

**Comment by taukakao** [comment]
> Imho, brltty should be banned out of the box, and only added for people with special needs.

One of the core ideas behind VanillaOS is that we ship the same image to everyone, so we can properly test everything and problems can't be caused by some particular configuration. This would be the exact opposite of that idea.

But I do know that brltty causes a lot of problems. So maybe it just doesn't work well enough to be included into Vanilla. This needs to be discussed further.

**Comment by trau-mar** [comment]
I agree with you. But if you cannot use your universal USB interface because it targets only one specific hardware, than this is clearly a bug. If now the software is removed or fixed, this is up to the developers. I just wanted to report the facts which are: /dev/ttyUSB0 isn't usable (by Arduino), /dev/ttyACM0 is not concerned.
