### ISSUE TITLE
Add a way to switch desktop environments, similar to blend's tracks

### ISSUE THREAD

**Issue by EitanMM** [Vanilla-OS/desktop-image#237]
### Feature Description

A way to switch between DEs and their associated packages seemlessly 

### Rationale

This feature would allow people who prefer other DEs than gnome to use vanilla without needing a custom image, alongside being easier than switching in most distros

### Additional Information

I feel that this is the only feature blendos has which vanilla is outright missing

**Comment by taukakao** [comment]
Testing every one of these DEs and maintaing compatibility with them is currently not feasible for us.
Everyone who wants to make a community image with a specific desktop environment is welcome to do so. The process is currently too hard though so what we can do is make this process easier. 
I created #238 for that.
