### ISSUE TITLE
The console is very broken

### ISSUE THREAD

**Issue by iWisp360** [Vanilla-OS/desktop-image#24]
When I installed VanillaOS on vm, the first thing i did meanwhile passing through the first setup is opening the Gnome Console, but is very broken and installing apps is painful without it, the terminal is the heart of Linux

**Comment by axtloss** [comment]
Please provide more information on what is broken and how exactly to reproduce it. We will not be able to resolve the issues without more information.

**Comment by iWisp360** [comment]
The console doesn't open after the first setup (on restricted shell, the one that creates user) ends. The second first setup on the normal session continues, as the gnome apps are installing, but when i try to open the console, it does nothing, it does not open

**Comment by axtloss** [comment]
This is due to recent changes/experiments with the terminal. Switch to a tty and run `vso pico-init` then switch back to gnome (it's on tty2) and it'll work.
