### ISSUE TITLE
Support for Xencelabs Devices

### ISSUE THREAD

**Issue by hrstwn** [Vanilla-OS/desktop-image#241]
### Feature Description

Please add this driver for all Xencelabs devices, including tablets, pen displays, and Quick Keys. The driver can be found here [https://www.xencelabs.com/support/download-drivers](https://www.xencelabs.com/support/download-drivers)

### Rationale

I need it for my device, and other people too, maybe

### Additional Information

Thank you

**Comment by taukakao** [comment]
We can't include proprietary drivers since they would be included in every installation of VanillaOS which many people would really not like.

Not sure if it would even be legal for us to do so.

**Comment by taukakao** [comment]
You will have to use a https://github.com/vanilla-os/custom-image/

**Comment by hrstwn** [comment]
I see. Thanks!
