### ISSUE TITLE
add libfuse2 package

### ISSUE THREAD

**Issue by iWisp360** [Vanilla-OS/desktop-image#26]
Launch of appimages is imposible without this package, and it does not install in the first setup

**Comment by mirkobrombin** [comment]
fuse2 is deprecated and will not [receive security fixes](https://www.cvedetails.com/vulnerability-list.php?vendor_id=3090&product_id=0&version_id=0&page=1&hasexp=0&opdos=0&opec=0&opov=0&opcsrf=0&opgpriv=0&opsqli=0&opxss=0&opdirt=0&opmemc=0&ophttprs=0&opbyp=0&opfileinc=0&opginf=0&cvssscoremin=0&cvssscoremax=0&year=0&cweid=0&order=1&trc=5&sha=04362d83280f8efe4c0f9668df424235042af263). It is now replaced by fuse3.
The Appimage runtime already supports fuse3 https://github.com/AppImage/type2-runtime/pull/6 it It's up to each app developer to use the new runtime.

**Comment by iWisp360** [comment]
is there a way to install it in Vanilla(as well as any core library)
