### ISSUE TITLE
Yellow accent color to make Gnome Vanillaish?

### ISSUE THREAD

**Issue by Thatoo** [Vanilla-OS/desktop-image#52]
Hello,

I now the vanilla gnome experience has a blue accent color : 

![image](https://github.com/Vanilla-OS/desktop-image/assets/464782/69f7634b-b934-4f4e-adda-ef46faf94b51)

but it doesn't match the Vanilla yellow ambiance. Why not just changing this color to make the design more vanilaish?

![image](https://github.com/Vanilla-OS/desktop-image/assets/464782/27b926fe-54be-4026-a02c-1d1127067f7c)

Waiting for the draft to be merged, https://gitlab.gnome.org/GNOME/gnome-shell/-/merge_requests/2715, it is possible to do so with the help of this extension : https://extensions.gnome.org/extension/5547/custom-accent-colors/

It would be nice to change also the color on the login screen though. This extension doesn't do that.
Ad ideally the color of folders too.

**Comment by taukakao** [comment]
I agree that this is a good idea once it's implemented in gnome but I'm very much against using an extension here. 

Theming everything is exactly what makes a lot of distros (manjaro, ubuntu, etc.) a lot worse then they would be without it.
Having a yellow accent color is really not worth it currently.

**Comment by taukakao** [comment]
This is back on the table now, since we're upgrading to Gnome 47.
