### ISSUE TITLE
pkexec doesn't work in tty

### ISSUE THREAD

**Issue by taukakao** [Vanilla-OS/desktop-image#79]
### Issue Description

When using the tty, you can't use pkexec to authenticate due to a "Not Authorized" error.

### Steps to Reproduce

- open a tty with "Ctrrl+Alt+F6"
- log in
- pkexec ls

### On what version of Vanilla OS this happens?

Unreleased

**Comment by Teh404Gal2** [comment]
seems like the issue is from upstream polkit, as their default fallback agent has been broken for 10 years... wow

**Comment by Teh404Gal2** [comment]
bug fix was released in Feb 9th but last pkexec release was in January 17

**Comment by Teh404Gal2** [comment]
will attempt to merge the bug fix into the older version using the debian sources

**Comment by Teh404Gal2** [comment]
im too stupid to actually package pkexec with the bug fix so if anyone wants to here's the patch file from the pr: https://patch-diff.githubusercontent.com/raw/polkit-org/polkit/pull/423.patch

im just awaiting approval of my salsa account so i can suggest it to debian's team

**Comment by Teh404Gal2** [comment]
patched polkit files in Teh404Gal/VanillaFork, will upload the modified debian source stuff in a zip in this issue
[Uploading polkitbugfixin.zip…]()
this included the modified source, and the debs

**Comment by taukakao** [comment]
This was fixed upstream.
