### ISSUE TITLE
Can't lock screen with shortcuts

### ISSUE THREAD

**Issue by Mars7x** [Vanilla-OS/desktop-image#82]
### Issue Description

GNOME has a default shortcut to lock the screen, which is Super + L, however it doesn't appear to work. Binding it to anything else also doesn't seem to work.

### Steps to Reproduce

- Press Super + L or whatever you have 'Lock screen' binded to.
- Screen does not lock.

### On what version of Vanilla OS this happens?

Unreleased

### Additional Information

FWIW, this shortcut worked fine on any other distro.

**Comment by taukakao** [comment]
It's because of https://github.com/Vanilla-OS/desktop-image/commit/ce5f8af805b42c52aadd1ed784a4cf2e31b93b71
