### ISSUE TITLE
Increase vm.max_map_count

### ISSUE THREAD

**Issue by Mars7x** [Vanilla-OS/desktop-image#85]
### Feature Description

vm.max_map_count is currently at 65530. This can cause issues in some games, such as crashes. This is why steamOS has it set to 2147483642 by default. 

### Rationale

Despite there not being that many, some games need a higher memory mapping to work properly, so I believe this change is important to fix those certain games.

### Additional Information

As far as I know, this does not have any drawbacks. Here is the [Fedora 39 Proposal](https://fedoraproject.org/wiki/Changes/IncreaseVmMaxMapCount) for some more information.

**Comment by axtloss** [comment]
Arch has done this too as seen in [this announcement]( https://archlinux.org/news/increasing-the-default-vmmax_map_count-value/), changing it on vanilla would be quite easy and there do not seem to be any issues caused by this

**Comment by mirkobrombin** [comment]
I support this
