### ISSUE TITLE
Opening Gnome Settings stops responding

### ISSUE THREAD

**Issue by ghost** [Vanilla-OS/desktop-image#88]
### Issue Description

First boot of the Vanilla OS 2 beta, go to open Gnome settings, browse the System and it crashes immediately. 
![image](https://github.com/Vanilla-OS/live-iso/assets/74065636/ada62171-d106-4fa3-968e-684d7f3da387)

### Steps to Reproduce

- Boot fresh vanilla os installation
- Open Gnome settings from app launcher "Activities"
- Go to System

### On what version of Vanilla OS this happens?

Unreleased

**Comment by kbdharun** [comment]
Thanks for reporting this issue, this issue is no longer present in the recent build (with the updated GNOME Settings package, I would suggest updating your installation to the recent image using the `vso sys-upgrade upgrade` command).
