### ISSUE TITLE
Wifi passwords lost after every upgrade

### ISSUE THREAD

**Issue by fluoriteByte** [Vanilla-OS/desktop-image#98]
### Issue Description

Every upgrade after the EtcBuilder fix has had this bug where none of the wifi passwords get saved, at all.
and for some weird reason the wifi settings are saved

this has happened 3 times now (out of 3 upgrades)

everything that depends on /etc is working fine, renaming the printer does save it
so its just the wifi password

### Steps to Reproduce

i had a broken A partition because of the EtcBuilder bug, i fixed it by rsyncing /var/lib/abroot/vos-b to vos-a
- have had the abroot etc syncing bug before, and have it fixed
- run abroot upgrade
- system is upgraded
- reboot and log in
- lack of wifi
- enter wifi password for it to work

### On what version of Vanilla OS this happens?

Unreleased

### Additional Information

- Running: Vanilla OS 2
- currently on a custom build, it doesnt seem to be the issue since i only added cloudflare warp, fprintd, usbutils, and fish

**Comment by fluoriteByte** [comment]
related to https://github.com/Vanilla-OS/ABRoot/issues/270

**Comment by taukakao** [comment]
Fixed in EtcBuilder
